/* ⚠️ This file was generated by the `wyrd` project.
   It is intentionally checked in — this is the non-generated header
   for the core Rust library that will be built in later phases. */

#ifndef WYRD_CORE_H
#define WYRD_CORE_H

/* Phase 1 is Python-based for fast iteration.
   This header is a placeholder for the Rust rewrite. */

#endif /* WYRD_CORE_H */
