"""
wyrd — HTML Export (Phase 3: Explorer Mode).

Generate a self-contained HTML page showing a generated world.
"""

from .world import World, TERRAIN, ADVENTURE_ZONE_TYPES
from .render import render_lore, render_factions, render_brief


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>wyrd — Seed {seed}</title>
<style>
  :root {{
    --bg: #1a1a2e;
    --surface: #16213e;
    --text: #e0e0e0;
    --accent: #e94560;
    --muted: #888;
  }}
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{
    background: var(--bg);
    color: var(--text);
    font-family: 'JetBrains Mono', 'Fira Code', 'Cascadia Code', 'Consolas', monospace;
    font-size: 14px;
    line-height: 1.5;
    padding: 2rem;
    max-width: 1200px;
    margin: 0 auto;
  }}
  h1 {{
    font-size: 1.5rem;
    margin-bottom: 0.25rem;
    color: var(--accent);
  }}
  .subtitle {{
    color: var(--muted);
    margin-bottom: 1.5rem;
    font-size: 0.85rem;
  }}
  .map {{
    font-size: {font_size}px;
    line-height: 1.15;
    letter-spacing: 0;
    white-space: pre;
    background: var(--surface);
    padding: 1rem;
    border-radius: 8px;
    overflow-x: auto;
    margin-bottom: 1.5rem;
  }}
  .legend {{
    display: flex;
    flex-wrap: wrap;
    gap: 1rem;
    margin-bottom: 1.5rem;
    font-size: 0.85rem;
  }}
  .legend-item {{
    display: flex;
    align-items: center;
    gap: 0.4rem;
  }}
  .legend-char {{
    font-size: 1rem;
    min-width: 1.2rem;
    text-align: center;
  }}
  .regions {{
    margin-bottom: 1.5rem;
  }}
  .regions h2 {{
    font-size: 1rem;
    color: var(--accent);
    margin-bottom: 0.5rem;
  }}
  .region {{
    margin-bottom: 0.3rem;
  }}
  .region-name {{
    color: #ffd700;
  }}
  .region-detail {{
    color: var(--muted);
    margin-left: 1rem;
  }}
  .lore {{
    white-space: pre-wrap;
    font-size: 0.85rem;
    line-height: 1.6;
    background: var(--surface);
    padding: 1rem;
    border-radius: 8px;
    margin-bottom: 1.5rem;
  }}
  .footer {{
    color: var(--muted);
    font-size: 0.75rem;
    text-align: center;
    margin-top: 2rem;
    border-top: 1px solid #333;
    padding-top: 1rem;
  }}
  a {{ color: var(--accent); }}
</style>
</head>
<body>
<h1>wyrd — Seed {seed}</h1>
<div class="subtitle">{brief}</div>
{snapshot_banner_html}

<div class="map">{map_html}</div>

<div class="legend">{legend_html}</div>

<div class="regions">
<h2>Regions</h2>
{regions_html}
</div>

{factions_html}

{bestiary_html}

<div class="lore">{lore_html}</div>

<div class="footer">
  Generated by <a href="https://github.com/shift-zero/wyrd">wyrd</a>
  — seed {seed} — {date}
</div>
</body>
</html>
"""


def _terrain_color_hex(terrain_key: str) -> str:
    """Map terrain types to hex colors for HTML."""
    colors = {
        "deep_water": "#005f87",
        "shallow": "#0087af",
        "sand": "#d7af87",
        "grass": "#afaf00",
        "forest": "#005f00",
        "hills": "#875f00",
        "mountains": "#af5f00",
        "snow": "#ffffff",
        "river": "#00afd7",
    }
    return colors.get(terrain_key, "#888")


def _settlement_color(char: str) -> str:
    """HTML color for settlement markers."""
    return "#ffd700"


def _ruin_color_hex() -> str:
    """Dim red for abandoned settlement ruins."""
    return "#660000"


def export_world_html(
    world: World,
    snapshot_year: int | None = None,
    abandoned_settlements: list[dict] | None = None,
    population_record: list[dict] | None = None,
    sim_events_count: int = 0,
) -> str:
    """Export a world as a self-contained HTML page.

    Args:
        world: The world to export (may have sim state applied)
        snapshot_year: If provided, shows a simulation snapshot banner
        abandoned_settlements: List of {name, x, y} for abandoned/ruined settlements
        population_record: List of {year, total_population, ...} from sim state
        sim_events_count: Total number of sim events that occurred
    """
    # ── Build ruin lookup ───────────────────────────────────────────
    ruins: dict[tuple[int, int], str] = {}
    if abandoned_settlements:
        for r in abandoned_settlements:
            ruins[(r["x"], r["y"])] = r.get("name", "Ruins")

    # ── Build map rows ──────────────────────────────────────────────
    map_rows = []
    for y in range(world.height):
        row_chars = []
        for x in range(world.width):
            terrain_key = world.terrain[y][x]
            hex_color = _terrain_color_hex(terrain_key)
            char = TERRAIN[terrain_key]["char"]

            # Check for ruin first (abandoned settlement)
            if (x, y) in ruins:
                row_chars.append(
                    f'<span style="color:{_ruin_color_hex()};font-weight:bold" '
                    f'title="{ruins[(x, y)]} (ruins)">⁂</span>'
                )
                continue

            # Check for active settlement
            settlement_char = None
            for region in world.regions:
                for s in region.settlements:
                    if s.x == x and s.y == y:
                        settlement_char = s.char
                        break
                if settlement_char:
                    break

            if settlement_char:
                row_chars.append(
                    f'<span style="color:#ffd700;font-weight:bold">{settlement_char}</span>'
                )
                continue

            # Check for adventure zone
            zone_at = None
            for z in world.adventure_zones:
                if z.x == x and z.y == y:
                    zone_at = z
                    break
            if zone_at:
                z_info = ADVENTURE_ZONE_TYPES.get(zone_at.zone_type, {})
                # Map zone color codes to hex
                zone_hex_colors = {
                    "dungeon": "#d70000", "cave": "#bcbcbc",
                    "ruin": "#870000", "tower": "#d7af5f",
                    "grove": "#00af00", "lair": "#d70000",
                    "shrine": "#875fff", "mine": "#d78700",
                }
                z_hex = zone_hex_colors.get(zone_at.zone_type, "#ffd700")
                row_chars.append(
                    f'<span style="color:{z_hex};font-weight:bold" '
                    f'title="[{zone_at.char}] {zone_at.name} — {z_info.get("desc", "")}'
                    f' | Difficulty: {zone_at.difficulty}'
                    f' | Inhabitants: {zone_at.inhabitants}'
                    f'{" | Quest: " + zone_at.quest_hook[:60] if zone_at.quest_hook else ""}'
                    f' | Treasure Tier: {zone_at.treasure_tier}'
                    f'">'
                    f'{zone_at.char}</span>'
                )
            else:
                row_chars.append(
                    f'<span style="color:{hex_color}">{char}</span>'
                )
        map_rows.append("".join(row_chars))

    map_html = "\n".join(map_rows)

    # ── Legend ──────────────────────────────────────────────────────
    legend_items = []
    for key, info in TERRAIN.items():
        hex_color = _terrain_color_hex(key)
        legend_items.append(
            f'<div class="legend-item">'
            f'<span class="legend-char" style="color:{hex_color}">{info["char"]}</span>'
            f'<span>{info["desc"]}</span>'
            f'</div>'
        )
    legend_items.append(
        f'<div class="legend-item">'
        f'<span class="legend-char" style="color:#ffd700;font-weight:bold">●</span>'
        f'<span>Settlement</span>'
        f'</div>'
    )
    # Adventure zone legend
    zone_hex_colors = {
        "dungeon": "#d70000", "cave": "#bcbcbc",
        "ruin": "#870000", "tower": "#d7af5f",
        "grove": "#00af00", "lair": "#d70000",
        "shrine": "#875fff", "mine": "#d78700",
    }
    for key, info in ADVENTURE_ZONE_TYPES.items():
        z_hex = zone_hex_colors.get(key, "#ffd700")
        legend_items.append(
            f'<div class="legend-item">'
            f'<span class="legend-char" style="color:{z_hex};font-weight:bold">{info["char"]}</span>'
            f'<span>{info["desc"]}</span>'
            f'</div>'
        )
    legend_html = "\n".join(legend_items)

    # ── Regions ─────────────────────────────────────────────────────
    region_parts = []
    for region in world.regions:
        settlements = ", ".join(
            f'{s.name} ({s.kind})' for s in region.settlements
        )
        region_parts.append(
            f'<div class="region">'
            f'<span class="region-name">{region.name}</span> '
            f'<span class="region-detail">({region.biome}) — {settlements}</span>'
            f'</div>'
        )
    regions_html = "\n".join(region_parts)

    # ── Factions ────────────────────────────────────────────────────
    factions_html = ""
    if world.factions:
        from .faction import FACTION_TYPES, RELATIONSHIP_ICONS, RELATIONSHIP_COLORS
        faction_lines = []
        for f in sorted(world.factions, key=lambda x: x.power_score, reverse=True):
            ft = FACTION_TYPES.get(f.faction_type, {})
            leader = f"{f.leader_title} {f.leader_name}" if f.leader_name else "(no leader)"
            terr = ", ".join(f.territory) if f.territory else "(none)"
            faction_lines.append(
                f'<details style="margin-bottom:0.5rem;background:var(--surface);'
                f'padding:0.5rem;border-radius:4px;">'
                f'<summary style="cursor:pointer;font-weight:bold;">'
                f'{ft.get("icon", "?")} {f.name}'
                f'<span style="color:#888;font-weight:normal;margin-left:0.5rem;">'
                f'[{ft.get("desc", "Unknown")}] — Power {f.power_score}/300'
                f'</span>'
                f'</summary>'
                f'<div style="margin-top:0.3rem;font-size:0.8rem;color:#ccc;">'
                f'<div>Leader: {leader}</div>'
                f'<div>Territory: {terr}</div>'
                f'<div>Influence: {f.influence} | Wealth: {f.wealth} | Military: {f.military} | Stability: {f.stability}</div>'
                f'<div>Reputation: {f.reputation}</div>'
                f'<div style="margin-top:0.2rem;font-style:italic;">{f.description}</div>'
            )
            if f.goals:
                faction_lines.append(f'<div style="margin-top:0.2rem;">Goals:</div>')
                for g in f.goals:
                    faction_lines.append(f'<div style="margin-left:1rem;color:#aaa;">→ {g}</div>')
            faction_lines.append('</div></details>')

        factions_html = (
            '<div class="regions" style="margin-top:1rem;">'
            '<h2>Factions</h2>'
            + "\n".join(faction_lines) +
            '</div>'
        )

        # Relationships
        if world.faction_relationships:
            rel_lines = ['<div style="margin-top:0.5rem;margin-bottom:1rem;font-size:0.85rem;">']
            rel_lines.append('<strong>Inter-Faction Relationships:</strong>')
            for rel in world.faction_relationships:
                r_icon = RELATIONSHIP_ICONS.get(rel.rel_type, "·")
                r_color = f"#{RELATIONSHIP_COLORS.get(rel.rel_type, 250):02x}{250:02x}{250:02x}"  # fallback
                rel_lines.append(f'<div style="margin-left:1rem;color:#aaa;">{r_icon} {rel.description}</div>')
            rel_lines.append('</div>')
            factions_html += "\\n".join(rel_lines)

    # ── Bestiary ────────────────────────────────────────────────────
    bestiary_html = ""
    if world.bestiary:
        beast_lines = []
        for c in sorted(world.bestiary, key=lambda x: x.tier, reverse=True):
            type_label = c.creature_type.replace("_", " ")
            tier_stars = "✦" * c.tier
            unique_tag = " ★" if c.is_unique else ""
            faction_tag = f" ⚑ {c.faction_affiliation}" if c.faction_affiliation else ""
            abilites = "; ".join(c.special_abilities[:2])
            beast_lines.append(
                f'<details style="margin-bottom:0.3rem;background:var(--surface);'
                f'padding:0.4rem;border-radius:4px;font-size:0.8rem;">'
                f'<summary style="cursor:pointer;font-weight:bold;">'
                f'{c.size[0].upper()} {c.name}{unique_tag}'
                f'<span style="color:#888;font-weight:normal;margin-left:0.5rem;">'
                f'[{type_label}] CR {c.challenge_rating} {tier_stars}{faction_tag}'
                f'</span>'
                f'</summary>'
                f'<div style="margin-top:0.3rem;color:#ccc;">'
                f'<div>{c.description}</div>'
                f'<div style="margin-top:0.2rem;color:#888;">'
                f'Habitat: {c.habitat} · Behavior: {c.behavior.replace("_", " ")} · {c.size} · {c.body_plan}'
                f'</div>'
                f'<div style="margin-top:0.2rem;"><strong>AC</strong> {c.stat_block["armor_class"]} · '
                f'<strong>HP</strong> {c.stat_block["hit_points"]} · '
                f'<strong>Damage</strong> {c.stat_block["damage_per_round"]}'
                f'</div>'
            )
            if c.special_abilities:
                beast_lines.append(f'<div style="margin-top:0.2rem;"><strong>Abilities:</strong> {abilites}</div>')
            if c.loot:
                loot_str = "; ".join(c.loot[:3])
                beast_lines.append(f'<div style="color:#aa0;">Loot: {loot_str}</div>')
            beast_lines.append('</div></details>')

        bestiary_html = (
            '<div class="regions" style="margin-top:1rem;">'
            '<h2>Bestiary</h2>'
            + "\\n".join(beast_lines) +
            '</div>'
        )

    # ── Lore ────────────────────────────────────────────────────────
    lore_text = render_lore(world) if world.lore else "(no lore generated)"
    # Strip ANSI escape codes for HTML
    import re
    lore_clean = re.sub(r'\x1b\[[0-9;]*m', '', lore_text)
    lore_html = lore_clean.replace("\n", "<br>")

    # ── Brief ───────────────────────────────────────────────────────
    brief = render_brief(world)

    # ── Font size based on world dimensions ─────────────────────────
    font_size = max(6, min(14, int(600 / max(world.width, 1))))

    # ── Snapshot banner ─────────────────────────────────────────────
    snapshot_banner_html = ""
    if snapshot_year is not None:
        total_pop = sum(s.population for r in world.regions for s in r.settlements)
        num_settlements = sum(len(r.settlements) for r in world.regions)

        # Population timeline chart (simple bar-based)
        timeline_html = ""
        if population_record and len(population_record) > 1:
            pops = [(r["year"], r["total_population"]) for r in population_record
                    if r["year"] % 25 == 0 or r == population_record[0] or r == population_record[-1]]
            if len(pops) < 3:
                pops = [(r["year"], r["total_population"]) for r in population_record]
            pop_max = max(p[1] for p in pops) if pops else 1
            pop_max = max(pop_max, 1)
            bar_entries = []
            for yr, p in pops:
                pct = max(5, int(p / pop_max * 80))
                bar_entries.append(
                    f'<div style="display:flex;align-items:center;gap:0.5rem;font-size:0.75rem;'
                    f'line-height:1.4">'
                    f'<span style="min-width:2.5rem;text-align:right;color:#888;">Y{yr}</span>'
                    f'<span style="display:inline-block;height:1rem;background:#e94560;border-radius:2px;'
                    f'width:{pct}%;min-width:2px;"></span>'
                    f'<span style="color:#ccc;">{p:,}</span>'
                    f'</div>'
                )
            timeline_html = (
                f'<div style="margin-top:0.75rem;padding-top:0.75rem;border-top:1px solid #333;">'
                f'<div style="font-size:0.75rem;color:#888;margin-bottom:0.25rem;">📈 Population Timeline</div>'
                + "".join(bar_entries) +
                f'</div>'
            )

        subtitle = f'{total_pop:,} souls across {num_settlements} settlements'
        if len(ruins) > 0:
            subtitle += f' · {len(ruins)} ruined'
        if sim_events_count > 0:
            subtitle += f' · {sim_events_count} events recorded'

        snapshot_banner_html = (
            f'<div style="background:#2a1a3e;padding:0.75rem 1rem;'
            f'border-radius:8px;margin-bottom:1rem;font-size:0.85rem;">'
            f'📜 <strong>Simulation Snapshot — Year {snapshot_year}</strong> &nbsp;|&nbsp; '
            f'{subtitle}'
            f'{timeline_html}'
            f'</div>'
        )

    # ── Date ────────────────────────────────────────────────────────
    from datetime import date
    today = date.today().isoformat()

    return HTML_TEMPLATE.format(
        seed=world.seed,
        brief=brief,
        snapshot_banner_html=snapshot_banner_html,
        map_html=map_html,
        legend_html=legend_html,
        regions_html=regions_html,
        factions_html=factions_html,
        bestiary_html=bestiary_html,
        lore_html=lore_html,
        font_size=font_size,
        date=today,
    )
