"""
wyrd — HTML Export (Phase 3: Explorer Mode).

Generate a self-contained HTML page showing a generated world.
"""

from .world import World, TERRAIN
from .render import render_lore, render_brief


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>wyrd — Seed {seed}</title>
<style>
  :root {{
    --bg: #1a1a2e;
    --surface: #16213e;
    --text: #e0e0e0;
    --accent: #e94560;
    --muted: #888;
  }}
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{
    background: var(--bg);
    color: var(--text);
    font-family: 'JetBrains Mono', 'Fira Code', 'Cascadia Code', 'Consolas', monospace;
    font-size: 14px;
    line-height: 1.5;
    padding: 2rem;
    max-width: 1200px;
    margin: 0 auto;
  }}
  h1 {{
    font-size: 1.5rem;
    margin-bottom: 0.25rem;
    color: var(--accent);
  }}
  .subtitle {{
    color: var(--muted);
    margin-bottom: 1.5rem;
    font-size: 0.85rem;
  }}
  .map {{
    font-size: {font_size}px;
    line-height: 1.15;
    letter-spacing: 0;
    white-space: pre;
    background: var(--surface);
    padding: 1rem;
    border-radius: 8px;
    overflow-x: auto;
    margin-bottom: 1.5rem;
  }}
  .legend {{
    display: flex;
    flex-wrap: wrap;
    gap: 1rem;
    margin-bottom: 1.5rem;
    font-size: 0.85rem;
  }}
  .legend-item {{
    display: flex;
    align-items: center;
    gap: 0.4rem;
  }}
  .legend-char {{
    font-size: 1rem;
    min-width: 1.2rem;
    text-align: center;
  }}
  .regions {{
    margin-bottom: 1.5rem;
  }}
  .regions h2 {{
    font-size: 1rem;
    color: var(--accent);
    margin-bottom: 0.5rem;
  }}
  .region {{
    margin-bottom: 0.3rem;
  }}
  .region-name {{
    color: #ffd700;
  }}
  .region-detail {{
    color: var(--muted);
    margin-left: 1rem;
  }}
  .lore {{
    white-space: pre-wrap;
    font-size: 0.85rem;
    line-height: 1.6;
    background: var(--surface);
    padding: 1rem;
    border-radius: 8px;
    margin-bottom: 1.5rem;
  }}
  .footer {{
    color: var(--muted);
    font-size: 0.75rem;
    text-align: center;
    margin-top: 2rem;
    border-top: 1px solid #333;
    padding-top: 1rem;
  }}
  a {{ color: var(--accent); }}
</style>
</head>
<body>
<h1>wyrd — Seed {seed}</h1>
<div class="subtitle">{brief}</div>
{snapshot_banner_html}

<div class="map">{map_html}</div>

<div class="legend">{legend_html}</div>

<div class="regions">
<h2>Regions</h2>
{regions_html}
</div>

<div class="lore">{lore_html}</div>

<div class="footer">
  Generated by <a href="https://github.com/shift-zero/wyrd">wyrd</a>
  — seed {seed} — {date}
</div>
</body>
</html>
"""


def _terrain_color_hex(terrain_key: str) -> str:
    """Map terrain types to hex colors for HTML."""
    colors = {
        "deep_water": "#005f87",
        "shallow": "#0087af",
        "sand": "#d7af87",
        "grass": "#afaf00",
        "forest": "#005f00",
        "hills": "#875f00",
        "mountains": "#af5f00",
        "snow": "#ffffff",
        "river": "#00afd7",
    }
    return colors.get(terrain_key, "#888")


def _settlement_color(char: str) -> str:
    """HTML color for settlement markers."""
    return "#ffd700"


def _ruin_color_hex() -> str:
    """Dim red for abandoned settlement ruins."""
    return "#660000"


def export_world_html(
    world: World,
    snapshot_year: int | None = None,
    abandoned_settlements: list[dict] | None = None,
    population_record: list[dict] | None = None,
    sim_events_count: int = 0,
) -> str:
    """Export a world as a self-contained HTML page.

    Args:
        world: The world to export (may have sim state applied)
        snapshot_year: If provided, shows a simulation snapshot banner
        abandoned_settlements: List of {name, x, y} for abandoned/ruined settlements
        population_record: List of {year, total_population, ...} from sim state
        sim_events_count: Total number of sim events that occurred
    """
    # ── Build ruin lookup ───────────────────────────────────────────
    ruins: dict[tuple[int, int], str] = {}
    if abandoned_settlements:
        for r in abandoned_settlements:
            ruins[(r["x"], r["y"])] = r.get("name", "Ruins")

    # ── Build map rows ──────────────────────────────────────────────
    map_rows = []
    for y in range(world.height):
        row_chars = []
        for x in range(world.width):
            terrain_key = world.terrain[y][x]
            hex_color = _terrain_color_hex(terrain_key)
            char = TERRAIN[terrain_key]["char"]

            # Check for ruin first (abandoned settlement)
            if (x, y) in ruins:
                row_chars.append(
                    f'<span style="color:{_ruin_color_hex()};font-weight:bold" '
                    f'title="{ruins[(x, y)]} (ruins)">⁂</span>'
                )
                continue

            # Check for active settlement
            settlement_char = None
            for region in world.regions:
                for s in region.settlements:
                    if s.x == x and s.y == y:
                        settlement_char = s.char
                        break
                if settlement_char:
                    break

            if settlement_char:
                row_chars.append(
                    f'<span style="color:#ffd700;font-weight:bold">{settlement_char}</span>'
                )
            else:
                row_chars.append(
                    f'<span style="color:{hex_color}">{char}</span>'
                )
        map_rows.append("".join(row_chars))

    map_html = "\n".join(map_rows)

    # ── Legend ──────────────────────────────────────────────────────
    legend_items = []
    for key, info in TERRAIN.items():
        hex_color = _terrain_color_hex(key)
        legend_items.append(
            f'<div class="legend-item">'
            f'<span class="legend-char" style="color:{hex_color}">{info["char"]}</span>'
            f'<span>{info["desc"]}</span>'
            f'</div>'
        )
    legend_items.append(
        f'<div class="legend-item">'
        f'<span class="legend-char" style="color:#ffd700;font-weight:bold">●</span>'
        f'<span>Settlement</span>'
        f'</div>'
    )
    legend_html = "\n".join(legend_items)

    # ── Regions ─────────────────────────────────────────────────────
    region_parts = []
    for region in world.regions:
        settlements = ", ".join(
            f'{s.name} ({s.kind})' for s in region.settlements
        )
        region_parts.append(
            f'<div class="region">'
            f'<span class="region-name">{region.name}</span> '
            f'<span class="region-detail">({region.biome}) — {settlements}</span>'
            f'</div>'
        )
    regions_html = "\n".join(region_parts)

    # ── Lore ────────────────────────────────────────────────────────
    lore_text = render_lore(world) if world.lore else "(no lore generated)"
    # Strip ANSI escape codes for HTML
    import re
    lore_clean = re.sub(r'\x1b\[[0-9;]*m', '', lore_text)
    lore_html = lore_clean.replace("\n", "<br>")

    # ── Brief ───────────────────────────────────────────────────────
    brief = render_brief(world)

    # ── Font size based on world dimensions ─────────────────────────
    font_size = max(6, min(14, int(600 / max(world.width, 1))))

    # ── Snapshot banner ─────────────────────────────────────────────
    snapshot_banner_html = ""
    if snapshot_year is not None:
        total_pop = sum(s.population for r in world.regions for s in r.settlements)
        num_settlements = sum(len(r.settlements) for r in world.regions)

        # Population timeline chart (simple bar-based)
        timeline_html = ""
        if population_record and len(population_record) > 1:
            pops = [(r["year"], r["total_population"]) for r in population_record
                    if r["year"] % 25 == 0 or r == population_record[0] or r == population_record[-1]]
            if len(pops) < 3:
                pops = [(r["year"], r["total_population"]) for r in population_record]
            pop_max = max(p[1] for p in pops) if pops else 1
            pop_max = max(pop_max, 1)
            bar_entries = []
            for yr, p in pops:
                pct = max(5, int(p / pop_max * 80))
                bar_entries.append(
                    f'<div style="display:flex;align-items:center;gap:0.5rem;font-size:0.75rem;'
                    f'line-height:1.4">'
                    f'<span style="min-width:2.5rem;text-align:right;color:#888;">Y{yr}</span>'
                    f'<span style="display:inline-block;height:1rem;background:#e94560;border-radius:2px;'
                    f'width:{pct}%;min-width:2px;"></span>'
                    f'<span style="color:#ccc;">{p:,}</span>'
                    f'</div>'
                )
            timeline_html = (
                f'<div style="margin-top:0.75rem;padding-top:0.75rem;border-top:1px solid #333;">'
                f'<div style="font-size:0.75rem;color:#888;margin-bottom:0.25rem;">📈 Population Timeline</div>'
                + "".join(bar_entries) +
                f'</div>'
            )

        subtitle = f'{total_pop:,} souls across {num_settlements} settlements'
        if len(ruins) > 0:
            subtitle += f' · {len(ruins)} ruined'
        if sim_events_count > 0:
            subtitle += f' · {sim_events_count} events recorded'

        snapshot_banner_html = (
            f'<div style="background:#2a1a3e;padding:0.75rem 1rem;'
            f'border-radius:8px;margin-bottom:1rem;font-size:0.85rem;">'
            f'📜 <strong>Simulation Snapshot — Year {snapshot_year}</strong> &nbsp;|&nbsp; '
            f'{subtitle}'
            f'{timeline_html}'
            f'</div>'
        )

    # ── Date ────────────────────────────────────────────────────────
    from datetime import date
    today = date.today().isoformat()

    return HTML_TEMPLATE.format(
        seed=world.seed,
        brief=brief,
        snapshot_banner_html=snapshot_banner_html,
        map_html=map_html,
        legend_html=legend_html,
        regions_html=regions_html,
        lore_html=lore_html,
        font_size=font_size,
        date=today,
    )
