"""
wyrd — HTML Export (Phase 3: Explorer Mode).

Generate a self-contained HTML page showing a generated world.
"""

from .world import World, TERRAIN
from .render import render_lore, render_brief


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>wyrd — Seed {seed}</title>
<style>
  :root {{
    --bg: #1a1a2e;
    --surface: #16213e;
    --text: #e0e0e0;
    --accent: #e94560;
    --muted: #888;
  }}
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{
    background: var(--bg);
    color: var(--text);
    font-family: 'JetBrains Mono', 'Fira Code', 'Cascadia Code', 'Consolas', monospace;
    font-size: 14px;
    line-height: 1.5;
    padding: 2rem;
    max-width: 1200px;
    margin: 0 auto;
  }}
  h1 {{
    font-size: 1.5rem;
    margin-bottom: 0.25rem;
    color: var(--accent);
  }}
  .subtitle {{
    color: var(--muted);
    margin-bottom: 1.5rem;
    font-size: 0.85rem;
  }}
  .map {{
    font-size: {font_size}px;
    line-height: 1.15;
    letter-spacing: 0;
    white-space: pre;
    background: var(--surface);
    padding: 1rem;
    border-radius: 8px;
    overflow-x: auto;
    margin-bottom: 1.5rem;
  }}
  .legend {{
    display: flex;
    flex-wrap: wrap;
    gap: 1rem;
    margin-bottom: 1.5rem;
    font-size: 0.85rem;
  }}
  .legend-item {{
    display: flex;
    align-items: center;
    gap: 0.4rem;
  }}
  .legend-char {{
    font-size: 1rem;
    min-width: 1.2rem;
    text-align: center;
  }}
  .regions {{
    margin-bottom: 1.5rem;
  }}
  .regions h2 {{
    font-size: 1rem;
    color: var(--accent);
    margin-bottom: 0.5rem;
  }}
  .region {{
    margin-bottom: 0.3rem;
  }}
  .region-name {{
    color: #ffd700;
  }}
  .region-detail {{
    color: var(--muted);
    margin-left: 1rem;
  }}
  .lore {{
    white-space: pre-wrap;
    font-size: 0.85rem;
    line-height: 1.6;
    background: var(--surface);
    padding: 1rem;
    border-radius: 8px;
    margin-bottom: 1.5rem;
  }}
  .footer {{
    color: var(--muted);
    font-size: 0.75rem;
    text-align: center;
    margin-top: 2rem;
    border-top: 1px solid #333;
    padding-top: 1rem;
  }}
  a {{ color: var(--accent); }}
</style>
</head>
<body>
<h1>wyrd — Seed {seed}</h1>
<div class="subtitle">{brief}</div>

<div class="map">{map_html}</div>

<div class="legend">{legend_html}</div>

<div class="regions">
<h2>Regions</h2>
{regions_html}
</div>

<div class="lore">{lore_html}</div>

<div class="footer">
  Generated by <a href="https://github.com/shift-zero/wyrd">wyrd</a>
  — seed {seed} — {date}
</div>
</body>
</html>
"""


def _terrain_color_hex(terrain_key: str) -> str:
    """Map terrain types to hex colors for HTML."""
    colors = {
        "deep_water": "#005f87",
        "shallow": "#0087af",
        "sand": "#d7af87",
        "grass": "#afaf00",
        "forest": "#005f00",
        "hills": "#875f00",
        "mountains": "#af5f00",
        "snow": "#ffffff",
        "river": "#00afd7",
    }
    return colors.get(terrain_key, "#888")


def _settlement_color(char: str) -> str:
    """HTML color for settlement markers."""
    return "#ffd700"


def export_world_html(world: World) -> str:
    """Export a world as a self-contained HTML page."""
    # ── Build map rows ──────────────────────────────────────────────
    map_rows = []
    for y in range(world.height):
        row_chars = []
        for x in range(world.width):
            terrain_key = world.terrain[y][x]
            hex_color = _terrain_color_hex(terrain_key)
            char = TERRAIN[terrain_key]["char"]

            # Check for settlement
            settlement_char = None
            for region in world.regions:
                for s in region.settlements:
                    if s.x == x and s.y == y:
                        settlement_char = s.char
                        break
                if settlement_char:
                    break

            if settlement_char:
                row_chars.append(
                    f'<span style="color:#ffd700;font-weight:bold">{settlement_char}</span>'
                )
            else:
                row_chars.append(
                    f'<span style="color:{hex_color}">{char}</span>'
                )
        map_rows.append("".join(row_chars))

    map_html = "\n".join(map_rows)

    # ── Legend ──────────────────────────────────────────────────────
    legend_items = []
    for key, info in TERRAIN.items():
        hex_color = _terrain_color_hex(key)
        legend_items.append(
            f'<div class="legend-item">'
            f'<span class="legend-char" style="color:{hex_color}">{info["char"]}</span>'
            f'<span>{info["desc"]}</span>'
            f'</div>'
        )
    legend_items.append(
        f'<div class="legend-item">'
        f'<span class="legend-char" style="color:#ffd700;font-weight:bold">●</span>'
        f'<span>Settlement</span>'
        f'</div>'
    )
    legend_html = "\n".join(legend_items)

    # ── Regions ─────────────────────────────────────────────────────
    region_parts = []
    for region in world.regions:
        settlements = ", ".join(
            f'{s.name} ({s.kind})' for s in region.settlements
        )
        region_parts.append(
            f'<div class="region">'
            f'<span class="region-name">{region.name}</span> '
            f'<span class="region-detail">({region.biome}) — {settlements}</span>'
            f'</div>'
        )
    regions_html = "\n".join(region_parts)

    # ── Lore ────────────────────────────────────────────────────────
    lore_text = render_lore(world) if world.lore else "(no lore generated)"
    # Strip ANSI escape codes for HTML
    import re
    lore_clean = re.sub(r'\x1b\[[0-9;]*m', '', lore_text)
    lore_html = lore_clean.replace("\n", "<br>")

    # ── Brief ───────────────────────────────────────────────────────
    brief = render_brief(world)

    # ── Font size based on world dimensions ─────────────────────────
    font_size = max(6, min(14, int(600 / max(world.width, 1))))

    # ── Date ────────────────────────────────────────────────────────
    from datetime import date
    today = date.today().isoformat()

    return HTML_TEMPLATE.format(
        seed=world.seed,
        brief=brief,
        map_html=map_html,
        legend_html=legend_html,
        regions_html=regions_html,
        lore_html=lore_html,
        font_size=font_size,
        date=today,
    )
